spin_version = "1"
authors = ["Raymundo Vásquez Ruiz <raymundo.vr@protonmail.com>"]
description = "Hello Spin"
name = "spin-hello-world"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-hello-world"
source = "target/wasm32-wasi/release/spin_hello_world.wasm"
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"
